FROM python:3.6

RUN mkdir noun_fetcher_enricher

WORKDIR /usr/src/app/noun_fetcher_enricher

COPY requirements.txt ./
COPY enricher.py ./

RUN mkdir noun_fetcher_enricher
COPY noun_fetcher_enricher/enricher_noun_fetcher.py ./noun_fetcher_enricher

ENV MODE=PROD
ENV PYTHONPATH .

RUN pip install --no-cache-dir -r requirements.txt

RUN python -m textblob.download_corpora

CMD ["python", "./noun_fetcher_enricher/enricher_noun_fetcher.py"]
#CMD tail -f /dev/null